FROM nginx
# FROM ubuntu:22.04
# RUN apt-get update
# RUN apt-get install nginx -y
# WORKDIR /etc/nginx/
# COPY nginx/nginx.conf .
# CMD ["nginx", "-g", "daemon off;"]

MAINTAINER Vadim Rudkovski <wadim_rudkovski@yahoo.com>
ENV TZ=Europe/Minsk

EXPOSE 80