- name: "Install docker modules"
  hosts: "VM"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Installing python3 modules"
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-selinux
        update_cache: true
        state: present

    - name: "Installing Docker"
      apt: 
        name: docker
        state: present        
        update_cache: true
    
    - name: "Ensure docker deamon is running"    
      service:
        name: docker
        state: started

    - name: "Starting Docker Service"
      service:
        name: docker
        state: started

    - name: "Copying Dockerfile"
      copy:
        src: /Users/admin/Documents/WORK/DEV OPS/Diplom/docker/Dockerfile
        dest: ./build/
        owner: root
        group: root
        mode: 666

    - name: "Building custom docker image"
      docker_image:
        name: "ubuntu_nginx:latest"
        source: build
        build:
          dockerfile: ./Dockerfile
          path: ./build
        state: present

    - name: "Running container"
      docker_container:
        name: "testdata"
        image: ubuntu_nginx:latest
        auto_remove: yes
        detach: yes
        state: started
        ports:
          - "80:80"
        mounts:
          - type: bind 
            source: /home/sadmin/script/html
            target: /usr/share/nginx/html
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost/"]
          interval: 5m
          timeout: 3s