- name: "Install docker"
  hosts: "VM"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    # - name: “Install python3”
    #   apt:
    #     update_cache: true
    #     name: python3
    #     state: present
    # - name: “Install python3-pip”
    #   apt:
    #     update_cache: true
    #     name: python3-pip
    #     state: present
    # - name: “Install python3-setuptools”
    #   apt:
    #     update_cache: true
    #     name: python3-setuptools
    #     state: present
    # - name: “Install selinux-python3”
    #   apt:
    #     update_cache: true
    #     name: python3-selinux
    #     state: present

    # - name: “Install PIP SIX”
    #   pip:
    #     name: six
    # - name: “Install PIP docker”
    #   pip:
    #     name: docker
    # - name: “Install requests sdk”
    #   pip:
    #     name: requests

    - name: "Start Docker Service"
      service:
        name: docker
        state: started

    - name: copy Dockerfiles
      copy:
        src: /Users/admin/Documents/WORK/DEV OPS/Diplom/docker/Dockerfile
        dest: ./build/
        owner: root
        group: root
        mode: 666
    
    - name: copy nginx config
      copy:
        src: /Users/admin/Documents/WORK/DEV OPS/Diplom/docker/nginx/nginx.conf
        dest: /home/sadmin/script/html/nginx/
        owner: sadmin
        group: sadmin
        mode: 666

    - name: build container image
      docker_image:
        name: "ubuntu_nginx:latest"
        source: build
        build:
          dockerfile: ./Dockerfile
          path: ./build
        state: present

    - name: run container
      docker_container:
        name: "testdata"
        image: ubuntu_nginx:latest
        auto_remove: yes
        detach: yes
        state: started
        ports:
          - "80:80"
        mounts:
          - type: bind 
            source: /home/sadmin/script/html
            target: /usr/share/nginx/html
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost/"]
          interval: 5m
          timeout: 3s
##

        
