---
- name: Deploying Docker
  hosts: "VM"
  become: true
  tasks:
    - name: Installing Docker
      apt: 
        state: "present"        
        name: "docker"
        update_cache: true
    
    - name: Ensure docker deamon is running
      become: true      
      service:
        name: docker
        state: started