---
- name: "Deploying the script"
  hosts: "VM"
  tasks:
    - name: "Copying script"
      copy:
        src: ../info.sh
        dest: ~/script/
        owner: "sadmin"
        group: "sadmin"
        mode: '0755'

    - name: "Executing script"
      become: true
      script: 
        chdir: /home/sadmin/script
        executable: /bin/bash
        cmd: ../info.sh
